import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { AuthProvider } from "./Services/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
      <body className={inter.className}>
        <AuthProvider>
          {/* <Header /> */}
          {children}
        </AuthProvider>
        </body>
    </html>
  );
}
